name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Flutter (pin stable 3.35.0)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.0"
          channel: "stable"
          cache: true

      - name: flutter --version
        run: flutter --version

      - name: Ensure Android folder exists
        run: |
          if [ ! -d "android" ]; then
            flutter create . --platforms=android
          fi

      - name: Patch minSdkVersion to 21
        run: |
          if grep -q "minSdkVersion" android/app/build.gradle; then
            sed -i 's/minSdkVersion [0-9][0-9]*/minSdkVersion 21/' android/app/build.gradle || true
          else
            awk '
              /defaultConfig *{/ {print; print "        minSdkVersion 21"; next}1
            ' android/app/build.gradle > tmp && mv tmp android/app/build.gradle
          fi

      - name: Flutter pub get
        run: flutter pub get

      - name: Build debug APK (installable)
        run: flutter build apk --debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: logiquest-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
