name: Build Android APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'
      - name: Create Android & iOS folders (if missing)
        run: flutter create . --platforms=android
      - name: Get dependencies
        run: flutter pub get
      - name: Build debug APK (installable)
        run: flutter build apk --debug
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: logiquest-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
