name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Flutter (stable 3.22.2)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: 'stable'
          cache: true

      # Instala Android SDK y paquetes necesarios
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          accept-android-sdk-licenses: true
          packages: |
            cmdline-tools;latest
            platform-tools
            platforms;android-34
            build-tools;34.0.0

      # Crea /android si falta y enlaza el SDK
      - name: Ensure Android project & local.properties
        run: |
          flutter create . --platforms=android
          echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties

      # Ajustes mínimos para compilar (ads requiere minSdk 21)
      - name: Patch Android SDK versions
        run: |
          if [ -f android/app/build.gradle ]; then
            sed -i 's/minSdkVersion [0-9]\+/minSdkVersion 21/' android/app/build.gradle || true
            sed -i 's/compileSdkVersion [0-9]\+/compileSdkVersion 34/' android/app/build.gradle || true
            sed -i 's/compileSdkVersion flutter\.compileSdkVersion/compileSdkVersion 34/' android/app/build.gradle || true
          fi
          if [ -f android/app/build.gradle.kts ]; then
            sed -i 's/minSdkVersion\s*=\s*[0-9]\+/minSdkVersion = 21/' android/app/build.gradle.kts || true
            sed -i 's/compileSdkVersion\s*=\s*[0-9]\+/compileSdkVersion = 34/' android/app/build.gradle.kts || true
          fi
          echo "org.gradle.jvmargs=-Xmx4096m -Dkotlin.daemon.jvm.options=-Xmx2048m" >> android/gradle.properties || true
          echo "android.useAndroidX=true" >> android/gradle.properties || true

      - name: Flutter pub get
        run: flutter pub get

      - name: Build debug APK
        run: flutter build apk --debug -v

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/**/*.apk
          if-no-files-found: error
